### ISSUE TITLE
After read card some times, NFC not work anymore

### ISSUE THREAD

**Issue by RyanYaoHZ** [NXPNFCLinux/nxpnfc_android_nougat#3]
Our sample is Hi3798mv200 + PN548C2 FW Ver: 100115
Read card(Type B) a few times, the NFC has no response. If we disable NFC in Andriod Setting or by program at that time, the system will be blocked.
Logcat:
[261617working.log](https://github.com/NXPNFCLinux/nxpnfc_android_nougat/files/3774686/261617working.log)
There are 6 times success reads( Cardtest app）in the log，after 6th read（CardTest: read end: 16:18:11.813), NFC did not work w/o any log and can only recover by reboot.

Can anyone help me on this issue?

**Comment by jgeslin** [comment]
That's weird !!!

Indeed, according to phTmlNfc_TmlWriterThread implementation (within external/libnfc-nci/halimpl/pn54x/tml/phTmlNfc.c) after trace:
> 10-26 16:18:10.812  2930  3123 D NxpTml  : PN54X - Invoking I2C Write.....

You should get trace `"PN54X - Error in I2C Write....."` or `"PN54X - I2C Write successful....."` (with potentially trace `"NxpNciX : len =  10 => 00000700A40000026002"` in between) as observed during the previous successful reads.

It seems like if the phTmlNfc_TmlWriterThread thread (number 3123) is locked (or killed) since there is no more related trace afterwards.

You may add more trace in this function to further investigate at what exact time the thread stops.

**Comment by RyanYaoHZ** [comment]
Very thanks for your advice! We have found the root cause. The interrupt type was set to "Level-triggered“. Changed to "Edge-triggered", the problem solved.
